spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/quan_ly_vat_tu?useUnicode=true&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: 123456789
